=== gitta6/V1C6ND_XMLGyak/XMLTaskV1C6ND/XMLSchemaV1C6ND.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="V1C6ND_okmanyiroda">
        <xs:complexType>
            <xs:sequence>

                <!-- DOLGOZÓK -->
                <xs:element name="dolgozo" type="dolgozotype" minOccurs="1" maxOccurs="unbounded"/>

                <!-- MUNKAKÖRÖK -->
                <xs:element name="munkakorok" type="munkakoroktype" minOccurs="1" maxOccurs="unbounded"/>

                <!-- SZEREP -->
                <xs:element name="szerep" type="szereptype" minOccurs="1" maxOccurs="unbounded"/>
  
                <!-- MUNKAKÖR ISMERETEK -->
                <xs:element name="munkakor_ism" type="munkakor_ismtype" minOccurs="1" maxOccurs="unbounded"/>

                <!-- ABLAK -->
                <xs:element name="ablak" type="ablaktype" minOccurs="1" maxOccurs="unbounded"/>

                <!-- ÜGYFÉL -->
                <xs:element name="ugyfel" type="ugyfeltype" minOccurs="1" maxOccurs="unbounded"/>

                <!-- FELETTES -->
                <xs:element name="felettes" type="felettestype" minOccurs="1" maxOccurs="unbounded"/>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Komplex típusok definíciói -->

    <!-- DOLGOZÓ típus -->
    <xs:complexType name="dolgozotype">
        <xs:sequence>
            <xs:element name="szig" type="xs:string"/>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="szulido" type="xs:date"/>
            <xs:element name="irsz" type="xs:string"/>
            <xs:element name="varos" type="xs:string"/>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hsz" type="xs:string"/>
            <xs:element name="fid" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="did" type="xs:integer" use="required"/>
    </xs:complexType>

    <!-- MUNKAKÖRÖK típus -->
    <xs:complexType name="munkakoroktype">
        <xs:sequence>
            <xs:element name="megnevezes" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="mid" type="xs:integer" use="required"/>
    </xs:complexType>

    <!-- SZEREP típus -->
    <xs:complexType name="szereptype">
        <xs:sequence>
            <xs:element name="helyettesit-e" type="xs:boolean"/>
        </xs:sequence>
        <xs:attribute name="did" type="xs:integer" use="required"/>
        <xs:attribute name="mid" type="xs:integer" use="required"/>
    </xs:complexType>

    <!-- MUNKAKÖR ISMERETEK típus -->
    <xs:complexType name="munkakor_ismtype">
        <xs:sequence>
            <xs:element name="ismeretek" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="mid" type="xs:integer" use="required"/>
    </xs:complexType>

    <!-- ABLAK típus -->
    <xs:complexType name="ablaktype">
        <xs:sequence>
            <xs:element name="ugykor" type="xs:string"/>
            <xs:element name="did" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="aid" type="xs:integer" use="required"/>
    </xs:complexType>

    <!-- ÜGYFÉL típus -->
    <xs:complexType name="ugyfeltype">
        <xs:sequence>
            <xs:element name="szig" type="xs:string"/>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="szulido" type="xs:date"/>
            <xs:element name="irsz" type="xs:string"/>
            <xs:element name="varos" type="xs:string"/>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hsz" type="xs:string"/>
            <xs:element name="aid" type="xs:integer"/>
            <xs:element name="belepes" type="xs:dateTime"/>
            <xs:element name="kilepes" type="xs:dateTime"/>
        </xs:sequence>
        <xs:attribute name="uid" type="xs:integer" use="required"/>
    </xs:complexType>

    <!-- FELETTES típus -->
    <xs:complexType name="felettestype">
        <xs:sequence>
            <xs:element name="szig" type="xs:string"/>
            <xs:element name="nev" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="fid" type="xs:integer" use="required"/>
    </xs:complexType>

</xs:schema>

=== gitta6/V1C6ND_XMLGyak/XMLTaskV1C6ND/XMLV1C6ND.xml
<?xml version="1.0" encoding="UTF-8"?>
<V1C6ND_okmanyiroda xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaV1C6ND.xsd">

    <!-- DOLGOZOK -->

    <dolgozo did="1" fid="1">
        <szig>14725AE</szig>
        <nev>Toth Erzsebet</nev>
        <szulido>1985-07-11</szulido>
        <irsz>3300</irsz>
        <varos>Eger</varos>
        <utca>Szechenyi ut</utca>
        <hsz>2</hsz>
    </dolgozo>

    <dolgozo did="2" fid="2">
        <szig>65815FV</szig>
        <nev>Nagy Zsigmond</nev>
        <szulido>1970-01-05</szulido>
        <irsz>3500</irsz>
        <varos>Miskolc</varos>
        <utca>Kossuth utca</utca>
        <hsz>36A</hsz>
    </dolgozo>

    <dolgozo did="3" fid="2">
        <szig>148575UK</szig>
        <nev>Kovacs Levente</nev>
        <szulido>1995-12-08</szulido>
        <irsz>3434</irsz>
        <varos>Malyi</varos>
        <utca>Petofi ut</utca>
        <hsz>50</hsz>
    </dolgozo>

    <!-- tovabbi dolgozo elemek -->

    <!-- MUNKAKOROK -->

    <munkakorok mid="1">
        <megnevezes>NAV ugyintezo</megnevezes>
    </munkakorok>

    <munkakorok mid="2">
        <megnevezes>gepjarmu ugyintezo</megnevezes>
    </munkakorok>

    <munkakorok mid="3">
        <megnevezes>CSOK ugyintezo</megnevezes>
    </munkakorok>
  
    <munkakorok mid="4">
        <megnevezes>palyazati ugyintezo</megnevezes>
    </munkakorok>


    <!-- tovabbi munkakorok elemek -->

    <!-- SZEREP -->

    <szerep did="1" mid="2">
        <helyettesit-e>0</helyettesit-e>
    </szerep>

    <szerep did="1" mid="3">
        <helyettesit-e>0</helyettesit-e>
    </szerep>

    <szerep did="1" mid="4">
        <helyettesit-e>0</helyettesit-e>
    </szerep>

    <szerep did="2" mid="1">
        <helyettesit-e>1</helyettesit-e>
    </szerep>

    <szerep did="3" mid="4">
        <helyettesit-e>0</helyettesit-e>
    </szerep>
    
    <szerep did="3" mid="2">
        <helyettesit-e>0</helyettesit-e>
    </szerep>

    <!-- tovabbi szerep elemek -->

    <!-- MUNKAKOR ISMERETEK -->

    <munkakor_ism mid="1"> 
        <ismeretek>adobevallas kezelese</ismeretek>
        <ismeretek>adozasi ismeretek</ismeretek>
    </munkakor_ism>

    <munkakor_ism mid="2"> 
        <ismeretek>MS Office ismeretek</ismeretek>
        <ismeretek>forgalmi engedely kezelese</ismeretek>
        <ismeretek>adasveteli szerzodes kezelese</ismeretek>
        <ismeretek>torzskonyv kezelese</ismeretek>
    </munkakor_ism>

    <munkakor_ism mid="3"> 
        <ismeretek>MS Office ismeretek</ismeretek>
        <ismeretek>jogi ismeretek</ismeretek>
        <ismeretek>szamviteli ismeretek</ismeretek>
    </munkakor_ism>
        
    <munkakor_ism mid="4">
        <ismeretek>MS Office ismeretek</ismeretek>
        <ismeretek>jogi ismeretek</ismeretek>
    </munkakor_ism>

    <!-- tovabbi munkakor_ism elemek -->

    <!-- ABLAK -->

    <ablak aid="1" did="2">
        <ugykor>adobevallas</ugykor>
    </ablak>

    <ablak aid="2" did="4">
        <ugykor>szemelyig.</ugykor>
    </ablak>

    <ablak aid="3" did="3">
        <ugykor>szemelyes iratok</ugykor>
    </ablak>

    <!-- tovabbi ablak elemek -->

    <!-- UGYFEL -->

    <ugyfel uid="1" aid="3">
        <szig>577403KE</szig>
        <nev>Hegyi Karoly</nev>
        <szulido>1969-09-15</szulido>
        <irsz>3432</irsz>
        <varos>Emod</varos>
        <utca>Kossuth ut</utca>
        <hsz>15</hsz>
        <belepes>2022-11-18T08:06:00</belepes>
        <kilepes>2022-11-18T08:24:00</kilepes>
    </ugyfel>

    <ugyfel uid="2" aid="1">
        <szig>775491HB</szig>
        <nev>Kis Elek</nev>
        <szulido>1979-04-05</szulido>
        <irsz>3300</irsz>
        <varos>Eger</varos>
        <utca>Petofi ut</utca>
        <hsz>6B</hsz>
        <belepes>2022-11-18T08:10:00</belepes>
        <kilepes>2022-11-18T08:25:00</kilepes>
    </ugyfel>

    <ugyfel uid="3" aid="2">
        <szig>224546DF</szig>
        <nev>Toth Maria</nev>
        <szulido>1980-12-25</szulido>
        <irsz>3400</irsz>
        <varos>Mezokovesd</varos>
        <utca>Matyas kiraly ut</utca>
        <hsz>189</hsz>
        <belepes>2022-11-18T08:11:00</belepes>
        <kilepes>2022-11-18T08:29:00</kilepes>
    </ugyfel>

    <!-- tovabbi ugyfel elemek -->

    <!-- FELETTES -->
    <felettes fid="1">
        <szig>468534WW</szig>
        <nev>Piros Rozsa</nev>
    </felettes>

    <felettes fid="2">
        <szig>795341AC</szig>
        <nev>Szabo Tamas</nev>
    </felettes>

    <felettes fid="3">
        <szig>861888JB</szig>
        <nev>Lengyel Laszlo</nev>
    </felettes>

    <!-- tovabbi felettes elemek -->

</V1C6ND_okmanyiroda>
